### ISSUE TITLE
Daniu Hy-01 and Hy-18 compatibility

### ISSUE THREAD

**Issue by Stormwing01** [GYelectronic/GY_LCD_MLX90640#2]
Hi,

Is this firmware only compatible with the daniu Hy-18, or is it also compatible with the Hy-01?

I'd appreciate any information :)

Edit: if not, could there perhaps be made a branch for the hy-01 as well?

Kind regards!

**Comment by GYelectronic** [comment]
I'm very sorry that hy-01 is not my product.

**Comment by Stormwing01** [comment]
> 
> 
> I'm very sorry that hy-01 is not my product.


That's alright :) have a good day!
