### ISSUE TITLE
Fahrenheit Version

### ISSUE THREAD

**Issue by ziggyone** [GYelectronic/GY_LCD_MLX90640#5]
This is a great little device!  A Fahrenheit version would be very attractive for the USA market.
Either an option to select Fahrenheit in setup, or a different firmware download with Fahrenheit instead of Celsius.  I would love to upgrade my device to Fahrenheit as I have no feel for the Celsius scale.

Thank you for considering.
Ziggy

**Comment by GYelectronic** [comment]
good idear.

**Comment by ziggyone** [comment]
Fahrenheit version works well!
Thank you.
