### ISSUE TITLE
Version 2.0  display bug

### ISSUE THREAD

**Issue by ziggyone** [GYelectronic/GY_LCD_MLX90640#6]
I have installed version 2.0 for Fahrenheit display. 
There is a small problem with the numbers. 

I have underlined the values in question, see attached photo.

If you look at the PHOTO FROM MANUAL (see attached photo), item #8, #9, and #10 are not converted to Fahrenheit properly in version 2.0.

In the VERSION 2.0 photo: the numbers under the color bar, 176 should be 80 F.    And 167 should be 75 F.  And 170 should be 77 F or 78 F.  They should correspond to Max: and Min: in Fahrenheit.

Also I believe item #7  should have 32 subtracted from it to make the default 0 in version 2.0.  Correct me if I am wrong.

Thank you for everything you have done.  It is very nice!

![ThermalComparison](https://user-images.githubusercontent.com/6013324/69880508-b1277d80-128f-11ea-8c5f-2e2e8c01cd3b.jpg)

**Comment by learning88** [comment]
nice,Thank you very much.

**Comment by GYelectronic** [comment]
Thank you very much for your feedback.

**Comment by ziggyone** [comment]
Version 2.1 fixed everything!
Thank you!
